includes:
- ./defaults.yaml

training:
  batch_size: 16
  max_updates: 48000
  num_workers: 0
  mlflow: true
  evaluation_interval: 2000
  early_stop:
    enabled: false
    criteria: total_loss
    minimize: true

evaluation:
  metrics:
  - nothing

dataset_config:
  textvqa:
    pretrain:
      type: mlm
      mlm_probability: 0.15
    use_images: false
    use_features: true
    max_features: 100
    zoo_requirements:
    - textvqa.defaults
    - textvqa.ocr_en
    features:
      train:
      - textvqa/defaults/features/open_images/detectron_attrs_max50_v0.lmdb,textvqa/ocr_azure/features/ocr_azure_frcn_features.lmdb,textvqa/ocr_en/features/ocr_en_frcn_features.lmdb
      val:
      - textvqa/defaults/features/open_images/detectron_attrs_max50_v0.lmdb,textvqa/ocr_azure/features/ocr_azure_frcn_features.lmdb,textvqa/ocr_en/features/ocr_en_frcn_features.lmdb
      test:
      - textvqa/defaults/features/open_images/detectron_attrs_max50_v0.lmdb,textvqa/ocr_azure/features/ocr_azure_frcn_features.lmdb,textvqa/ocr_en/features/ocr_en_frcn_features.lmdb
    annotations:
      train:
      - textvqa/defaults/annotations/imdb_train_ocr_azure.npy,textvqa/defaults/annotations/imdb_train_ocr_en.npy
      val:
      - textvqa/defaults/annotations/imdb_val_ocr_azure.npy,textvqa/defaults/annotations/imdb_val_ocr_en.npy
    processors:
      context_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          max_seq_length: 250
      obj_text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          max_seq_length: 100

model_config:
  m4c:
    losses:
      - type: mlm
    ocr:
      text_embedding: bert
      mmt_in_dim: 3420  # 768 (TEXT, 300 for fasttext) + 604 (PHOC) + 2048 (Faster R-CNN) + 0 (all zeros; legacy)
      normalize_bert: true
    obj:
      mmt_in_dim: 2816
      normalize_bert: true
