includes:
- ./defaults_azure_bertocr.yaml
checkpoint:
  resume: true
  resume_best: false
  resume_pretrained: true
  reset:
    all: true
dataset_config:
  textvqa:
    processors:
      obj_text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          max_seq_length: 100


model_config:
  m4c:
    ocr:
      normalize_bert: true
    obj:
      mmt_in_dim: 2816
      normalize_bert: true